import { Map, List, Record } from "immutable";

export default Map({
  urls: List([
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=189069",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=182234",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=188909",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=178351",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=185917",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=134824",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=189618",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=52515",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=67457",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=192247",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=192066",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=194799",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=193066",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=185273",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=182809",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=163788",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=177608",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=187351",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=194693",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=185269",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=183429",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=190355",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=191143",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=106360",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=195180",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=186239",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=187294",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=174261",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=136872",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=168051",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=185282",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=185150",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=189633",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=29059",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=10001",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=179307",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=185285",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=191642",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=134963",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=85825",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=185256",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=189747",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=10480",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=136870",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=14448",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=189624",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=36651",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=173247",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=179397",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=186348",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=171518",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=159311",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=168050",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=194368",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=186235",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=181099",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=37742",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=185292",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=182387",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=79770",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=156912",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=56220",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=179414",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=27111",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=179394",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=40932",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=109640",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=185151",
    "https://movie.naver.com/movie/bi/mi/basic.nhn?code=10323",
  ]),
  urlCounter: 69,
  commonTags: List([
    "#content > div.article > div.mv_info_area > div.mv_info > h3 > a:nth-child(1)",
    "#content > div.article > div.section_group.section_group_frst > div:nth-child(1) > div > div > h5",
  ]),
  tagCounter: 2,
});

export const stateHead = Map({
  url: "URL",
  tags: List([]),
});

export const stateRow = Record({ url: "", tagResult: List([]) });

export const stateRows = List([
  stateRow({ url: "url01", tagResult: List(["tag01", "tag02"]) }),
  stateRow({ url: "url02", tagResult: List(["tag11", "tag12"]) }),
]);
